//! API -> APPLICATION PROGRAMMING INTERFACE

//? APIS DEL NAVEGADOR WEB
/*
- LOCAL STORAGE -> ALMACENAMIENTO LOCAL
- FETCH API -> PETICION A SERVIDOR
- HISTORY API -> HISTORIAL DE LA PAGINA
- VALIDATION API -> VALIDAR FORMULARIOS
ETC..
*/

//? APIS EXTERNAS
/*
- ACCEDER A RECURSOS DE OTRAS PARTES (EJ YOUTUBE): VIDEOS, CANALES Y SUBIR VIDEOS 
ETC..
*/